### ISSUE TITLE
webpack + react support?

### ISSUE THREAD

**Issue by id0Sch** [chriszarate/sheetrock#88] opened 2016-02-11 00:52 UTC
Hi,
I'm trying to use the lib as a node module but using react and webpack
react's global has no document so requestJSONP function fails
and somehow it's trying to load the AMD type of the lib, and when removing it from the code it can't get request to actually be the lib - so the request fails....

I would appreciate if you could assist since this module made it so easy to use googlesheets.
I will try and figure out a solution as well..

Thanks!

**Comment by chriszarate** [comment] 2016-02-11 03:30
Interesting ... The issue is definitely that you are getting the AMD definition, which assumes browser/DOM/`requestJSONP`. I haven't used Webpack yet ... is there an updated Universal Module Definition that Webpack recommends?

**Comment by id0Sch** [comment] 2016-02-11 08:31
okay so i got webpack to not use AMD by setting the right config.
however i still got requestModule as empty object until i saw this in your package.json :
```
"browser": {
    "request": false
  },
```
only when i removed it and restarted my app that it worked.

p.s still haven't worked it out completely since I'm getting this error now:
```
Response to preflight request doesn't pass access control check:
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://xxx-xxx.xxxx.com' is therefore not allowed access.
```

**Comment by chriszarate** [comment] 2016-02-11 13:46
I'm confused about whether you are running your app on the server or in the browser, or both. On the server, Sheetrock should be calling requestJSON. On the browser, requestJSONP. That CORS error makes it sound like you are hitting requestJSON in the browser, which would mean that Webpack is probably doing something weird like browserifying the reuquest module (is your bundle enormous?). 

I think this comes down to the UMD at the top of Sheetrock, and whether it needs to be modified to accommodate Webpack or if Webpack's config can be tweaked to work with it. I won't be able to investigate in-depth until next week, but let me know if you uncover anything. If you could post your Webpack config here, that could help.

**Comment by id0Sch** [comment] 2016-02-11 13:53
i'm using it on the browser, but with node's request module, and yes - webpack does create a bundle
when i was using the requestJSONP i had issues since React does not have .document on global and the lib could not append the script to the head.

p.s - my bundle is 5MB

```
/**
 * Created by mynamehere on 31/01/2016.
 */
var path = require('path');
var webpack = require('webpack');
var config = require('./config');
var request = require('request');

var webpackConfig = {
    devtool: 'eval',
    entry: [`webpack-dev-server/client?http://${config.devServer.host}:${config.devServer.port}`, // WebpackDevServer host and port
        'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
        './js/app.jsx'], // Your appʼs entry point
    output: {
        path: path.join(__dirname, 'dist'),
        publicPath: '/dist/',
        filename: 'bundle.js'
    },
    module: {
        noParse: [/node_modules\/json-schema\/lib\/validate\.js/, /node_modules\\json-schema\\lib\\validate\.js/],
        loaders: [
            {
                test: /\.js/, loader: 'imports?define=>false',
                include: [
                    path.join(__dirname, 'node_modules', 'sheetrock')
                ]
            },
            {test: /\.json$/, loader: 'json'},
            {
                test: /\.jsx$/,
                loaders: ['react-hot', 'babel'],
                include: [
                    path.join(__dirname, 'js')
                ]
            },
            {
                test: /\.scss$/,
                loaders: ["style", "css", "sass"]
            }
        ]
    },
    resolve: {
        root: [path.resolve(__dirname, 'js'), path.resolve(__dirname, 'node_modules')],
        //alias: {
        //    request: require.resolve('request')
        //},
        //you can now require('file') instead of require('file.coffee')

        extensions: ['', '.js', '.json', '.jsx', '.webpack.js', '.web.js']
    },
    resolveLoader: {
        root: path.join(__dirname, 'node_modules'),
        packageMains: ['json']
    },
    node: {
        console: true,
        fs: 'empty',
        net: 'empty',
        tls: 'empty'
    },
    //externals : ['request'],
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ]
};
require('./server')(config, webpackConfig);
module.exports = webpackConfig;
```

**Comment by id0Sch** [comment] 2016-02-11 15:50
what about doing this
that way you don't append the callback function to the document
```
 function requestJsonp(url, callback){
   var callbackName = "jsonpCallback" + Math.floor(Math.random() * 100000000000);
   window[callbackName] = function (data) {
      delete window[callbackName];
      callback.apply(data);
   }
   var url = "http://example.com/?callback=" + callbackName;
   // Insert script tag for jsonp request here
 }
```

**Comment by id0Sch** [comment] 2016-02-11 15:50
my bad, sorry

**Comment by chriszarate** [comment] 2016-02-17 12:37
I should have a fix/guidance for this tonight. WebPack doesn't care a whit about the UMD. Since it handles both AMD and CommonJS, it just uses the first one it sees. My mistake was in assuming AMD would only be used in the browser.

**Comment by id0Sch** [comment] 2016-02-17 12:44
thanks!

**Comment by chriszarate** [comment] 2016-02-19 05:44
I've updated Sheetrock to `1.0.1`. After you update, you shouldn't need any special Webpack config—and in fact you should remove the loader you added for Sheetrock (`imports?define=>false`).

A quick note: In the browser, Sheetrock expects and depends on the DOM. React may use a virtual DOM, but `window.document` will still be present, and Sheetrock uses it to initiate JSONP requests. It will however, be up to you to use callbacks to integrate returned data into React.

**Comment by chriszarate** [comment] 2016-02-21 16:08
Closing, please feel free to reopen if the issue persists.

**Closed by chriszarate** 2016-02-21 16:08 UTC
